version: "3.8"

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  fastapi:
    build: .
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      - postgres
