version: "3.8"

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test:
        ["CMD-SHELL", "psql -U $POSTGRES_USER -d $POSTGRES_DB -c 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - data123:/var/lib/postgresql/data

  fastapi:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  data123:
